
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  AWSAccountId:
    Type: String
    Description: "AWS Account ID where the resources will be deployed"
    Default: "083846066460"

Resources:
  # Create Amazon ECR Repository
  ZayzoonECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "zayzoon-app"
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images older than 14 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 14
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Environment
          Value: Zayzoon

  # Create ECS Cluster
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: "ZayzoonCluster"
      Tags:
        - Key: Environment
          Value: Zayzoon

  # Define ECS Task Definition
  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: "ZayzoonApp"
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWSAccountId}:role/ZayzoonECSRole"
      NetworkMode: "awsvpc"
      RequiresCompatibilities:
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ContainerDefinitions:
        - Name: "ZayzoonAppContainer"
          Image: !Sub "${AWSAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/zayzoon-app:latest"
          Memory: 512
          Cpu: 256
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: "/ecs/ZayzoonApp"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "ecs"
      Tags:
        - Key: Environment
          Value: Zayzoon